#!/bin/sh -e

export JAVAC="/usr/bin/jikes"
export BOOTCLASSPATH="none"

./configure --disable-Werror \
	--disable-gmp \
	--disable-gtk-peer \
	--disable-gconf-peer \
	--disable-plugin \
	--disable-dssi \
	--disable-alsa \
	--disable-gjdoc \
	--with-jikes="/usr/bin/jikes" \
	--bindir="/usr/libexec/gnuclasspath-093" \
	--with-glibj-dir="/usr/share/classpath" \
	--includedir="/usr/include/classpath" \
	--prefix="/usr"

make DESTDIR="$1"
make DESTDIR="$1" install

