#!/bin/sh -e

#export BOOTCLASSPATH="/usr/lib/jvm/usr/share/jamvm/classes.zip:/usr/lib/jvm/usr/share/classpath/glibj.zip"

#export JAVACMD="${JAVA_HOME}/bin/jamvm"
#export JAVAC="${JAVA_HOME}/bin/jikes"
#export CLASSPATH="/usr/lib/jvm/rt.jar"
#sed -i -e 's/depends="jars,test-jar"/depends="jars"/' build.xml

#export BOOTJAVAC_OPTS="-nowarn"
#export ANT_OPTS="-Dbuild.compiler=jikes"
#
#./bootstrap.sh

mkdir -pv $1/usr/lib/jvm/etc
mkdir -pv $1/usr/lib/jvm/usr/lib
mkdir -pv $1/usr/lib/jvm/usr/bin

cp -r lib/* $1/usr/lib/jvm/usr/lib/
cp -r etc/* $1/usr/lib/jvm/etc/
cp -r bin/ant $1/usr/lib/jvm/usr/bin/
cp -r bin/antRun $1/usr/lib/jvm/usr/bin/
