#!/bin/sh -e

rm -v lib/classes.zip

export JAVAC="/usr/bin/jikes"
patch -p1 < classes-location.patch
patch -p1 < no-fpu-control.patch 
#sed -i -e "s/return CLASSPATH_INSTALL_DIR\"\/lib\/classpath\";/return CLASSPATH_INSTALL_DIR\"\/lib\/jamvm-1.5.1\/classpath\";/g" src/dll.c || die "Sed failed!"
autoreconf --force --install

./configure --enable-ffi \
	--disable-int-caching \
	--enable-runtime-reloc-checks \
	--prefix="/usr/jamvm" \
	--datadir="/usr/share" \
	--bindir="/usr/bin" \
	--with-classpath-install-dir="/usr" 

make

make DESTDIR="$1" install

mkdir $1/usr/jamvm/bin
ln -s /usr/bin/jamvm $1/usr/jamvm/bin/java
ln -s /usr/bin/jikes $1/usr/jamvm/bin/javac
ln -s /usr/bin/fastjar $1/usr/jamvm/bin/jar


