#!/bin/sh -e

rm -v lib/classes.zip

export JAVAC="/usr/lib/jvm/usr/bin/jikes"
patch -p1 < classes-location.patch
patch -p1 < no-fpu-control.patch 
#sed -i -e "s/return CLASSPATH_INSTALL_DIR\"\/lib\/classpath\";/return CLASSPATH_INSTALL_DIR\"\/lib\/jamvm-1.5.1\/classpath\";/g" src/dll.c || die "Sed failed!"
autoreconf --force --install

./configure --enable-ffi \
	--disable-int-caching \
	--enable-runtime-reloc-checks \
	--prefix="/usr/lib/jvm/usr" \
	--with-classpath-install-dir="/usr/lib/jvm/usr"

make

make DESTDIR="$1" install
ln -s /usr/lib/jvm/usr/bin/jamvm $1/usr/lib/jvm/usr/bin/java
ln -s /usr/lib/jvm/usr/bin/jikes $1/usr/lib/jvm/usr/bin/javac
ln -s /usr/bin/fastjar $1/usr/lib/jvm/usr/bin/jar


